conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('inbox', views.inbox, name='inbox'),
    path('detail/<int:pk>/', views.detail_inbox, name='detail'),
]

core/urls.py
from django.urls import path
from . import views
app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("new-item/", views.new_item, name="new-item"),
    path("edit-item/<int:pk>/", views.edit_item, name="edit-item"),
    path("detail/<pk>/", views.detail, name="detail"),
    path("delete/<int:pk>/", views.delete_view, name="delete"),
]

steve_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('conversation/', include('conversation.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.TextField()

    is_sold = models.BooleanField(default=False)
    stock = models.IntegerField()

    created_by = models.ForeignKey(User, related_name="products", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Product

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email',  'password1', 'password2']

    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter Username","class": "form-control"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"placeholder": "Enter Email","class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Password","class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password","class": "form-control"}))

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter Username", "class": "form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Password", "class": "form-control"}))

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "price", "description", "is_sold", "stock", "image"]

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "price", "description", "is_sold", "stock", "image"]

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterForm, UserLoginForm, AddProductForm, EditProductForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from. models import Product


# Create your views here.
def home(request):
    products = Product.objects.all()

    context = {'products': products}
    return render(request, 'core/home.html', context)

def signup(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("core:home")

    else:
        form = RegisterForm()

    context = {"form": form}
    return render(request, "core/signup.html", context)

def login_view(request):

    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("core:home")

    else:
        form = UserLoginForm()

    context = {"form": form}
    return render(request, "core/login.html", context)
def logout_view(request):
    logout(request)
    return redirect("core:login")

@login_required
def new_item(request):
    form = AddProductForm()

    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()
            return redirect("core:login")

    context = {"form": form}
    return render(request, "core/form.html", context)

@login_required
def edit_item(request, pk):

    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    form = EditProductForm(instance=product)

    if request.method == "POST":
        form = EditProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect("core:home")

    context = {
        "form": form,
        "product": product
        }
    return render(request, "core/form.html", context)

def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)

    context = {
        "product": product,
        "related_products": related_products,
    }
    return render(request, "core/detail.html", context)

def delete_view(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    if request.method == "POST":
        product.delete()
        return redirect("core:home")

    context = {
            "product": product,
    }
    return render(request, "core/delete.html", context)

templates/core/delete.html
 {% extends "core/index.html" %}

    {% block title %}Delete{% endblock title %}

    {% block content %}
    <h1>Delete</h1>
        <form action="" method="POST">
            {% csrf_token %}

            <p class="my-5">Are you sure that you want to delete <strong>"{{ product.name }}"</strong>?</p>

            <a href="{% url 'core:detail' product.pk %}" class="btn btn-success">Back</a>
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
        </form>

    {% endblock content %}

templates/core/detail.html
{% extends 'core/index.html' %}

    {% block title %}{{ product.name }} Detail{% endblock title %}

    {% block content %}

    <h1>{{ product.name }} - Detail Page</h1>

    <div class="card mb-3" style="max-width: 90%;">
      <div class="row g-0">
        <div class="col-md-5">
          <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5><br>
            <p class="card-text">${{ product.price }}</p><br>
            <p class="card-text"><strong>Description:</strong><br>{{ product.description }}</p>

            <br>
            <hr>

            {% if request.user == product.created_by %}
              <a href="{% url 'core:edit-item' product.pk %}" class="btn btn-success">Edit</a>
            <a href="{% url 'core:delete' product.pk %}" class="btn btn-danger">Delete</a>

            {% else %}
              <a href="{% url 'conversation:new' product.id %}" class="btn btn-primary">Contact Seller</a>

            {% endif %}

          </div>
        </div>
      </div>
    </div>

    <br>

    <h1>Related Products</h1>

    <div class="row">
      {% if related_products %}
        {% for product in related_products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.image.url }}" class="card-img-top" alt="..." height="250;" border="2px solid green;">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{% url 'core:detail' product.pk %}" class="btn btn-primary">View</a>

              </div>
            </div>
        </div>

        {% endfor %}
      {% else %}
        <p>There is no related products for this category</p>
      {% endif %}
    </div>
{% endblock content %}

templates/core/form.html
{% extends "core/index.html" %}
{% block title %}New Product{% endblock title %}
{% block content %}
    <h1>Add New Product</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
{% endblock content %}

templates/core/home.html
{% extends 'core/index.html' %}
{% block content %}
<div class="row">
        {% for product in products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.image.url }}" class="card-img-top" alt="..." width="250" height="300">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">₦{{ product.price }}</p>
                <a href="{% url 'core:detail' product.pk %}" class="btn btn-primary">Detail</a>

              </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content%}

templates/core/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static  'css/styles.css' %}">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'core:login' %}">Login</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'core:new-item' %}">Add Item</a></li>
            <li><a class="dropdown-item" href="{% url 'conversation:inbox' %}">Inbox</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'core:signup' %}">Signup</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control mx-auto" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <div class="container">
        {% block content %}
        {% endblock content%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/login.html
{% extends "core/index.html" %}
{% block title %}Login{% endblock title %}
{% block content %}
    <h1>Login</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-success" type="submit">Login</button>
    </form>
    <br>
  <p><small>Don't have an account</small><a href="{% url 'core:signup' %}">Signup</a></p>
{% endblock content %}

templates/core/signup.html
{% extends "core/index.html" %}
{% block title %}Signup{% endblock title %}
{% block content %}
    <h1>Signup</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <br>
    <p><small>Already have an account</small> <a href="{% url 'core:login' %}">Login</a></p>
{% endblock content %}